mode = "dark"

accent = "#FFD84A"
selection = "#173070"
muted = "#6578B5"

background = "#05060D"
dark_background = "#030409"
darker_background = "#010205"
lighter_background = "#0A1024"

foreground = "#F5F2D8"
dark_foreground = "#6578B5"
light_foreground = "#C8C9D4"
bright_foreground = "#FFFCEB"

red = "#FF4A55"
yellow = "#FFD84A"
orange = "#FF9A3C"
green = "#73E36C"
cyan = "#4DEBFF"
blue = "#386AFF"
magenta = "#FF5CA8"
brown = "#A86B45"

bright_red = "#FF7179"
bright_yellow = "#FFE778"
bright_green = "#98F38F"
bright_cyan = "#7AF3FF"
bright_blue = "#5D86FF"
bright_magenta = "#FF86C0"

selection_background = "#173070"
selection_foreground = "#FFFCEB"
